services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${database}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./password_backend
    environment:
      user: ${user}
      host: ${host} 
      database: ${database}
      password: ${password}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
